### ISSUE TITLE
pip install fails with Python 3.9.0

### ISSUE THREAD

**Issue by mcpiroman** [biosustain/swiglpk#39] opened 2020-10-22 16:14 UTC
I reckon this is the same thing as with #36, except now with python 3.9.0, the error log is analogous.

**Comment by Viech** [comment] 2020-12-03 14:52
With my [AUR package](https://aur.archlinux.org/packages/python-swiglpk/), I get a different error message since upgrading to Python 3.9:
```
Exception: Could not find glpk.h! Maybe glpk or glpsol is not installed.
```
This is with glpk 4.65 installed and `/usr/include/glpk.h` is present. The same PKGBUILD (which is doing essentially just `python setup.py install --root="${pkgdir}" --optimize=1`) worked fine with Python 3.8.

**Comment by Viech** [comment] 2020-12-08 15:37
I can also confirm that it does not install via pip, _even if GLPK is installed locally_. The error is as follows:

```shell
% pip install --user swiglpk
Collecting swiglpk
  Using cached swiglpk-4.65.1.tar.gz (30 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5ne4an67/swiglpk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5ne4an67/swiglpk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-krgimqx0
         cwd: /tmp/pip-install-5ne4an67/swiglpk/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5ne4an67/swiglpk/setup.py", line 53, in <module>
        copy_glpk_header()
      File "/tmp/pip-install-5ne4an67/swiglpk/setup.py", line 44, in copy_glpk_header
        raise Exception('Could not find glpk.h! Maybe glpk or glpsol is not installed.')
    Exception: Could not find glpk.h! Maybe glpk or glpsol is not installed.
    Trying to determine glpk.h location
    glpk.h found at /include/glpk.h
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Unfortunately, the build toolchain of [PICOS](https://gitlab.com/picos-api/picos) always uses the latest stable Python version and depends on swiglpk installed via pip for generating the online documentation. This means that I cannot easily release a new version of PICOS until swiglpk is available via pip for Python 3.9. This is normally not a huge deal but as I'm about to hand in a thesis that refers to an unpublished version of PICOS, it would be a great help if this could be fixed within the next two weeks.

**Comment by Viech** [comment] 2020-12-17 13:41
I had some time to look into this further and my issue is in fact different from the one reported by @mcampodonico (i.e. #36). Both issues appear to be caused by the fact that no wheels are provided yet so that `setupy.py install` is used by `pip`. In #36, it looks like all that is missing is `swig` (`unable to execute 'swig': No such file or directory`), so @mcampodonico should be able to work around their issue by installing `swig`. Maybe `swiglpk` can somehow list `swig` as a build dependency so that a more meaningful error is produced.

For my problem I'll open another issue.

**Comment by carrascomj** [comment] 2021-02-24 13:01
[swiglpk 5.0.0](https://pypi.org/project/swiglpk/) now works in python3.9. Please note that the macosx wheels are not there yet due to problems with deployment.

**Closed** 2022-01-10 23:40 UTC
